name: Publish Docker image

on:
  push:
    branches: [ master ]

env:
  DOCKER_REPO: cs3120project5

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: echo "post-checkout" && ls -lah && pwd
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{ env.DOCKER_REPO }}:latest
